### ISSUE TITLE
rename denord to descord (or something else)

### ISSUE THREAD

**Issue by ktiy** [amatiasq/deno#1]
denord already exists at https://github.com/denosaurs/denord

**Comment by amatiasq** [comment]
Why not to rename that one?

**Comment by ktiy** [comment]
becuz it's been around longer than yours;
it would be nice just to avoid confusion

++ there's already sort of a discord deno module community, of which denord is already a part of

**Comment by amatiasq** [comment]
> becuz it's been around longer than yours;

How do you know that? if you check the commit history you'll see the folder was copied from a different, private repository.

> it would be nice just to avoid confusion

Exactly, but that's a reason to change any, not this one.

> ++ there's already sort of a discord deno module community, of which denord is already a part of

That's no reason to change the name of this project.

This library is the one actually registered in deno.land: https://deno.land/x/denord

I see no reason to go through the effort of changing the name in this project and the ones that depend on it.

This will not happen unless strong reason is provided.

**Comment by eliassjogreen** [comment]
Hi! Considering your module denord seems to have gone stale and has not been updated in ~3 months we over at [Denosaurs](https://github.com/denosaurs) would like to kindly ask you if you would be willing to give us the deno.land/x name. Your version of denord does not work with the current version of deno which our does and we are a few dedicated open-sources which will maintain our module.

Thanks, Elias and the Denosaurs team :D

**Comment by lucacasonato** [comment]
@amatiasq To make this as friction-less as possible for you: _if_ you do want to give the name to the nice people working on https://github.com/denosaurs/denord, just let me know. I will transfer the name without any effort required on your part :-)

**Comment by amatiasq** [comment]
Sorry for being a dick.

Thanks @lucacasonato that would be nice, have to sleep now.

**Comment by eliassjogreen** [comment]
No worries! Thanks!
